# -*- coding: utf-8 -*-
"""KNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIT6SuHjcg9iDqBj2HUYQ4DMkcO3ntcA
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

col_names=["sepallength","sepalwidth","petallength","petalwidth","class"]
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
dataset=pd.read_csv(url,names=col_names)

dataset

dataset_knn=dataset.values[:,0:4]
labels=dataset.values[:,-1]

dataset_knn

import math
def distance(x1,x2):
  distances=0.0
  for i in range(len(x1)):
    distances+=(x1[i]-x2[i])**2
  return(math.sqrt(distances))

testing_data=dataset.values[115,0:4]

distance_cumm=[]
for i in range(len(dataset_knn)):
  distance_cumm.append([distance(dataset_knn[i],testing_data),labels[i]])

distance_cumm.sort()

distance_cumm

k=10
first_k=[]
for i in range(1,k+1):
  first_k.append(distance_cumm[i][1])
first_k

from collections import Counter
count=Counter(first_k)
count

count.most_common(1)[0][0]

print("Our Final Predicted label is",count.most_common(1)[0][0])

