# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRvUx_DWwLh-_wPh0S_EMJ5sNnqToPtV
"""

pip install pyqrcode

pip install pypng

# Import QRCode from pyqrcode
import pyqrcode
import png
from pyqrcode import QRCode


# String which represents the QR code
s = "https://leetcode.com/problemset/"

# Generate QR code
url = pyqrcode.create(s)

# Create and save the svg file naming "myqr.svg"
url.svg("my1qr.svg", scale = 8)

# Create and save the png file naming "myqr.png"
url.png('m1yqr.png', scale = 6)